### ISSUE TITLE
Use parentNode's width and height instead of window's sizes.

### ISSUE THREAD

**Issue by f15u** [marcbruederlin/particles.js#11]
With a simple change the canvas can be limited to the container, even the body, when it's used as a background, e.g. in a header element.

```js
canvas.width = canvas.parentNode.offsetWidth;
canvas.height = canvas.parentNode.offsetHeight;
```

If it's ok for you, I can try to submit a PR.

**Comment by marcbruederlin** [comment]
A PR would be nice 👍
