### ISSUE TITLE
Particles.init not returning anything

### ISSUE THREAD

**Issue by paxelpixel** [marcbruederlin/particles.js#19]
I'm trying to pause animation with

```
  var particles = Particles.init({
         // options
       });
  particles.pauseAnimation();

```

however particles is undefined
the partcicles keep moving/animating

**Comment by marcbruederlin** [comment]
@jhonalino Are you initializing particles.js on window load? Check this fiddle if you need a working example: https://jsfiddle.net/b1b0q42x/
