### ISSUE TITLE
Set the canvas width and height using options

### ISSUE THREAD

**Issue by adityapurwa** [marcbruederlin/particles.js#20]
Current: The code inside particle is to create a canvas with 100% width and height.
Expected: Allow to use custom value for the canvas width and height.

I wanted to create a small-bottom-only particle background, this is why i need custom height values. I'd gladly work on it and create pull request if needed.

**Comment by marcbruederlin** [comment]
You can wrap your canvas. Particles.js is then using the dimensions of the parent element to render the canvas. Check this if you need a example: https://jsfiddle.net/m97g98sx/1/
