### ISSUE TITLE
How to destroy particles object

### ISSUE THREAD

**Issue by alangrainger** [marcbruederlin/particles.js#21]
Is there a way to destroy the particles object? I can't see anything obvious in the code.

I have a single-page app, and switching between routes causes an error when it can't find the canvas object on the second page.

Thanks!

**Comment by kainonly** [comment]
I have the same problem with Angular ,Do you solve it？ @alangrainger

**Comment by marcbruederlin** [comment]
@alangrainger @kainOnly I'll put it on my list for the next few days.

**Comment by kainonly** [comment]
Thanks!

**Comment by marcbruederlin** [comment]
Do you guys have a minimal demo to reproduce the problem?

**Comment by kainonly** [comment]
https://github.com/kainOnly/ng-ezbit.
resize page go wrong after login,I want to destroy particles after a successful login.
![tim 20180322231143](https://user-images.githubusercontent.com/9986159/37779498-830646d2-2e27-11e8-9ed8-c43ec7a3ea96.png)

**Comment by marcbruederlin** [comment]
I just updated the library. You can now use the public destroy method (`Particles.destroy()`).

**Comment by kainonly** [comment]
Thank you for your help. The problem has been solved.

**Comment by marcbruederlin** [comment]
@alangrainger Is this solved for you too?
